### ISSUE TITLE
Can use a bit more documentation

### ISSUE THREAD

**Issue by Bramzor** [negezor/snowyflake#1]
Looking for a snowflake lib so tested yours

snowyflake.ts:4:12 - error TS2737: BigInt literals are not available when targeting lower than ESNext.
Seems it only supports new versions of nodejs and only on ESNEXT?

Also a typo in the example. Should be Snowyflake instead of Snowlyflake

**Comment by negezor** [comment]
It is assumed that the latest version of TypeScript is used. And at the moment, BigInt is still experimental. That's why esnext is required. I updated the information required for installation.
